#!/usr/bin/env python3
"""Write the 2D surface files read by in.cyl and in.plate into geom/.

Points run clockwise around the body. With counter-clockwise ordering SPARTA
takes the interior of the body as the flow region and emits no particles.
"""
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
GEOM = os.path.join(HERE, "geom")


def write_surf(path, pts):
    n = len(pts)
    lines = [f"{i + 1} {i + 2 if i + 1 < n else 1}" for i in range(n)]
    with open(path, "w") as f:
        f.write("surf file generated by make_geom.py\n\n")
        f.write(f"{n} points\n{n} lines\n\nPoints\n\n")
        for i, (x, y) in enumerate(pts):
            f.write(f"{i + 1} {x:.10g} {y:.10g}\n")
        f.write("\nLines\n\n")
        for i, ln in enumerate(lines):
            f.write(f"{i + 1} {ln}\n")
    print("wrote", path, f"({n} pts, CW)")


def circle(R=0.05, N=120):
    return [(R * math.cos(-2 * math.pi * i / N), R * math.sin(-2 * math.pi * i / N))
            for i in range(N)]


def plate(c=0.1, t=0.006, aoa_deg=20.0, nchord=60, nthick=4):
    """Closed thin rectangle, clockwise from the leading edge at (0,0) to the
    trailing edge at (c,0), then rotated by the angle of attack."""
    pts = []
    for i in range(nchord):                      # upper surface, LE to TE
        pts.append((c * i / nchord, t / 2))
    for j in range(nthick):                      # trailing-edge face
        pts.append((c, t / 2 - t * j / nthick))
    for i in range(nchord):                      # lower surface, TE to LE
        pts.append((c * (nchord - i) / nchord, -t / 2))
    for j in range(nthick):                      # leading-edge face
        pts.append((0.0, -t / 2 + t * j / nthick))
    a = -math.radians(aoa_deg)                   # clockwise, so the lower surface is windward for flow along +x
    ca, sa = math.cos(a), math.sin(a)
    return [(x * ca - y * sa, x * sa + y * ca) for x, y in pts]


if __name__ == "__main__":
    os.makedirs(GEOM, exist_ok=True)
    write_surf(os.path.join(GEOM, "circle_D0.1.surf"), circle())
    write_surf(os.path.join(GEOM, "plate_c0.1_a20.surf"), plate())
