Last login: Wed Jun 22 19:52:55 on ttys001
chenyichong@c055035 ~ % ls
1st year PhD
2nd year PhD
3rd year Under
4th year Under
5th Postgraduate
Applications
C++ Primer Tutorial
CodesBackUp
Creative Cloud Files
Creative Cloud Files alandlerc@gmail.com b41193bc5ac7ea99c581a05af0f5b7900504c3b428b0ba7e9e52dcb355054ac5
Desktop
Dissertation_Edin
Dissertation_ICL
Documents
Downloads
Dropbox
Important_files
KineticTheory
Library
Movies
Music
MyPublications
OneDrive - University of Edinburgh
OneDrive_Edin
OneDrive_ICL
PersonalLife
PhD_Application
PhD_Preparation
Pictures
Public
Python_Learning
ScatteringKernels
Sites
TeachingSlides
mathematics
openFoam
opt
packages
yichong
chenyichong@c055035 ~ % ls
1st year PhD
2nd year PhD
3rd year Under
4th year Under
5th Postgraduate
Applications
C++ Primer Tutorial
CodesBackUp
Creative Cloud Files
Creative Cloud Files alandlerc@gmail.com b41193bc5ac7ea99c581a05af0f5b7900504c3b428b0ba7e9e52dcb355054ac5
Desktop
Dissertation_Edin
Dissertation_ICL
Documents
Downloads
Dropbox
Important_files
KineticTheory
Library
Movies
Music
MyPublications
OneDrive - University of Edinburgh
OneDrive_Edin
OneDrive_ICL
PersonalLife
PhD_Application
PhD_Preparation
Pictures
Public
Python_Learning
ScatteringKernels
Sites
TeachingSlides
mathematics
openFoam
opt
packages
yichong
chenyichong@c055035 ~ % archer
(yichongc@login.archer2.ac.uk) Password: 
#######################################################################################

        @@@@@@@@@
     @@@         @@@            _      ____     ____   _   _   _____   ____    ____
   @@@    @@@@@    @@@         / \    |  _ \   / ___| | | | | | ____| |  _ \  |___ \
  @@@   @@     @@   @@@       / _ \   | |_) | | |     | |_| | |  _|   | |_) |   __) |
  @@   @@  @@@  @@   @@      / ___ \  |  _ <  | |___  |  _  | | |___  |  _ <   / __/
  @@   @@  @@@  @@   @@     /_/   \_\ |_| \_\  \____| |_| |_| |_____| |_| \_\ |_____|
  @@@   @@     @@   @@@
   @@@    @@@@@    @@@       https://www.archer2.ac.uk/support-access/
     @@@         @@@
        @@@@@@@@@

 -         U K R I         -        E P C C        -         H P E   C r a y         -

Hostname:     ln03
Distribution: SLES 15.1 1
CPUS:         256
Memory:       515.5GB
Configured:   2022-06-14

######################################################################################
---------------------------------Welcome to ARCHER2-----------------------------------
######################################################################################

yichongc@ln03:~> ls
exampleScript  mylammps  work.sh
yichongc@ln03:~> RDF
yichongc@ln03:/general/d114/d114/yichongc> ls
Argon_300K  ArgonRough	Helium_300K  Helium_423K  HydrogenData	KerogenData  MaxwellData  Nitrogen_300K  PlatinumData  XenonData
yichongc@ln03:/general/d114/d114/yichongc> cd HydrogenData/
yichongc@ln03:/general/d114/d114/yichongc/HydrogenData> ls
Hydrogen_0.1MPa
yichongc@ln03:/general/d114/d114/yichongc/HydrogenData> cd Hydrogen_0.1MPa/
yichongc@ln03:/general/d114/d114/yichongc/HydrogenData/Hydrogen_0.1MPa> ls
bin  data.dat  in.equil  initialisation  in.meas  Makefile  run.slurm  Specification.dat  src
yichongc@ln03:/general/d114/d114/yichongc/HydrogenData/Hydrogen_0.1MPa> vim in.equil 
yichongc@ln03:/general/d114/d114/yichongc/HydrogenData/Hydrogen_0.1MPa> ls
bin  data.dat  in.equil  initialisation  in.meas  Makefile  run.slurm  Specification.dat  src
yichongc@ln03:/general/d114/d114/yichongc/HydrogenData/Hydrogen_0.1MPa> work
yichongc@ln03:/work/d114/d114/yichongc> ls
Argon_423K  ArgonTemp  MethanePlatinum	mylammps  NitrogenData	ScalingArcher2
yichongc@ln03:/work/d114/d114/yichongc> cd ArgonTemp/
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp> ls
ArgonFrozen100K  ArgonFrozen200K  ArgonFrozen300K  ArgonFrozen400K  ArgonTemp100K  ArgonTemp200K  ArgonTemp300K  ArgonTemp400K
ArgonFrozen150K  ArgonFrozen250K  ArgonFrozen350K  ArgonFrozen50K   ArgonTemp150K  ArgonTemp250K  ArgonTemp350K  ArgonTemp50K
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp> cd ArgonFrozen
-bash: cd: ArgonFrozen: No such file or directory
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp> cd ArgonFrozen100K/
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp/ArgonFrozen100K> ls
bin	  dump_equil_gas.lammpstrj  initialisation  log.equil	log.meas	 restart.3500000  run.slurm	     src
data.dat  dump_meas_gas.lammpstrj   in.meas	    log.lammps	Makefile	 restart.500000   slurm-1766568.out
DataDir   in.equil		    log_equil	    log_meas	restart.2000000  restart.5000000  Specification.dat
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp/ArgonFrozen100K> vim in.equil 
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp/ArgonFrozen100K> ls
bin	  dump_equil_gas.lammpstrj  initialisation  log.equil	log.meas	 restart.3500000  run.slurm	     src
data.dat  dump_meas_gas.lammpstrj   in.meas	    log.lammps	Makefile	 restart.500000   slurm-1766568.out
DataDir   in.equil		    log_equil	    log_meas	restart.2000000  restart.5000000  Specification.dat
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp/ArgonFrozen100K> vim Makefile 
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp/ArgonFrozen100K> ls
bin	  dump_equil_gas.lammpstrj  initialisation  log.equil	log.meas	 restart.3500000  run.slurm	     src
data.dat  dump_meas_gas.lammpstrj   in.meas	    log.lammps	Makefile	 restart.500000   slurm-1766568.out
DataDir   in.equil		    log_equil	    log_meas	restart.2000000  restart.5000000  Specification.dat
yichongc@ln03:/work/d114/d114/yichongc/ArgonTemp/ArgonFrozen100K> vim Makefile 

        ./$@
        mv $@ ${BIN}

# ------------------------------------------------------------
# Phony target, that it does not build anything

## PoiseData    : Compile the source codes for Poiseuille Flow simulation.
.PHONY : PoiseData
PoiseData : FlowRate Bins

.PHONY : AccommodationCoefficients
AccommodationCoefficients : ACs Collisions

.PHONY : ScatteringData
ScatteringData : FAngular PAngular ACs Bins Collisions Displacement FlowRate ResidenceTime Traj VirtualLayer FVDF PiVDF PrVDF

## collect      : Collect the auto-generated files
.PHONY : collect
collect :
        mv -f *.txt ${DataDir}
        mv -f *.dat ${DataDir}
        mv -f *.trj ${DataDir}
        mv -f *.xyz ${DataDir}
        mv ${DataDir}/Specification.dat ./
        mv ${DataDir}/data.dat ./

## clean        : Remove the auto-generated files
.PHONY : clean
clean :
        rm -f *.txt
        rm -f *.dat
        rm -f *.o

## q            : Monitoring jobs
.PHONY : q
q : 
        squeue -u $(USER)

## grep         : Extract the timesteps in the dumpfile
.PHONY : grep
grep : 
        grep -o 'TIMESTEP' dump_meas_gas.lammpstrj | wc -l

